// Generates supabase/seed.sql from the prototype's sample catalogue (members/prototype/src).
// Sample data only: replace with the real products before launch.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../../', import.meta.url));
const src = (f) => readFileSync(root + 'prototype/src/' + f, 'utf8');
const ctx = {};
new Function('ctx', src('i18n.js').replace(/const (LOCALES|I18N|PACK_TEXT|ART_TITLE|CHAPTERS|EXCERPT) =/g, 'ctx.$1 =') )(ctx);
const appSrc = src('app.js');
const packs = eval(appSrc.slice(appSrc.indexOf('const PACKS = [') + 'const PACKS = '.length, appSrc.indexOf('];', appSrc.indexOf('const PACKS = [')) + 1));

const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const locales = ['en', 'pt', 'es'];
const sections = [
  ['kids', 1, { en: 'For children', pt: 'Para crianças', es: 'Para niños' }],
  ['preach', 2, { en: 'For preachers and teachers', pt: 'Para pregadores e professores', es: 'Para predicadores y maestros' }],
  ['life', 3, { en: 'Christian living', pt: 'Vida cristã', es: 'Vida cristiana' }],
];

let sql = `-- Sample catalogue generated by supabase/scripts/generate-seed.mjs. Replace with real products before launch.\n\n`;
for (const [slug, order, names] of sections) {
  sql += `insert into public.sections (slug, sort_order) values (${q(slug)}, ${order});\n`;
  for (const l of locales) sql += `insert into public.section_translations (section_id, locale, name) select id, '${l}', ${q(names[l])} from public.sections where slug = ${q(slug)};\n`;
}
sql += '\n';
packs.forEach((p, i) => {
  sql += `insert into public.products (slug, type, section_id, gateway_product_id, price_cents, access, visibility, sort_order, field_colour, page_count, free_sample)
  select ${q(p.id)}, '${p.type}', s.id, ${q(p.gid)}, ${p.price * 100}, '${p.access}', '${p.vis}', ${i + 1}, ${q(p.field)}, ${p.pages}, ${p.type !== 'colouring'}
  from public.sections s where s.slug = ${q(p.sec)};\n`;
  for (const l of locales) {
    const t = ctx.PACK_TEXT[l][p.id];
    sql += `insert into public.product_translations (product_id, locale, title, description, verse, verse_ref) select id, '${l}', ${q(t.t)}, ${q(t.d)}, ${q(t.v)}, ${q(t.r)} from public.products where slug = ${q(p.id)};\n`;
  }
  if (p.type === 'colouring') {
    p.art.forEach((a, n) => {
      sql += `insert into public.product_pages (product_id, position, title) select id, ${n + 1}, ${q(ctx.ART_TITLE.en[a])} from public.products where slug = ${q(p.id)};\n`;
    });
  } else {
    for (const l of locales) {
      const chs = ctx.CHAPTERS[l][p.id], body = ctx.EXCERPT[l][p.id].map((x) => `<p>${x}</p>`).join('');
      chs.forEach((c, n) => {
        sql += `insert into public.product_chapters (product_id, locale, position, title, body_html, minutes, is_sample) select id, '${l}', ${n + 1}, ${q(c)}, ${q(body)}, ${p.mins[n]}, ${n === 0} from public.products where slug = ${q(p.id)};\n`;
      });
    }
  }
  sql += '\n';
});
writeFileSync(root + 'supabase/seed.sql', sql);
console.log('wrote supabase/seed.sql:', packs.length, 'products');
