# Áreas, serviços e planos do Kingdom InCompany v2.
# Preços base e descrições entre parêntesis: tabela enviada pelo cliente. Os outros planos ficam "Sob consulta".
AREAS=[
 dict(slug='consultoria-estrategica',nome='Consultoria Estratégica',andar=1,rot='Fundação',pilar='a-consultoria',ico='i-grafico',sub='Decisões com base em dados',
  tese='Decisões com base em dados, não em palpites.',
  texto='Analisamos o mercado, o modelo de negócio e os números da sua empresa para definir prioridades, metas, prazos e responsáveis. Depois acompanhamos a execução em sessões de Business Advising.',
  servicos=[dict(slug='business-plan',nome='Business Plan',longo='Desenvolvimento de Business Plan',inclui='Plano de negócios simplificado e Business Advising',preco='32.500 MT',unid='',
    resumo='Um plano de negócios claro, com números que se sustentam, e acompanhamento para o pôr em prática.',
    planos=[('Essencial','Para validar e organizar o negócio.','32.500 MT',['Plano de negócios simplificado','Análise de mercado e concorrência','Projeções financeiras base','Sessão de Business Advising']),
            ('Profissional','Para apresentar a investidores e bancos.',None,['Tudo do plano Essencial','Plano de negócios completo','Projeções financeiras a 5 anos','Pitch deck para investidores','Três sessões de Business Advising']),
            ('Premium','Para captar investimento e executar.',None,['Tudo do plano Profissional','Modelo financeiro editável','Preparação para reuniões com bancos e investidores','Acompanhamento da execução durante 3 meses'])])
  ],
  provisorios=[('Diagnóstico empresarial','O que trava o crescimento, com números'),('Planeamento estratégico','Prioridades, metas, prazos e responsáveis')]),
 dict(slug='desenvolvimento-editorial',nome='Desenvolvimento Editorial',andar=2,rot='Andar 2',pilar='a-editorial',ico='i-documento',sub='Documentos que convencem',
  tese='Documentos que apresentam a sua empresa ao nível do que ela já entrega.',
  texto='Damos forma escrita e visual ao valor da sua empresa: documentos com direção editorial e argumento comercial, prontos para reuniões, concursos e parcerias.',
  servicos=[
   dict(slug='perfil-corporativo',nome='Perfil Corporativo',longo='Desenvolvimento de Perfis Corporativos',inclui='Perfil corporativo até 15 páginas',preco='9.500 MT',unid='',
    resumo='O documento que apresenta a sua empresa em reuniões, propostas, parcerias e candidaturas a financiamento.',
    planos=[('Essencial','Para apresentar a empresa com clareza.','9.500 MT',['Perfil corporativo até 15 páginas','Entrevista de levantamento com a direção','Redação e revisão do texto','Paginação com a identidade da marca','PDF pronto a enviar']),
            ('Profissional','Para empresas com várias áreas ou projetos.',None,['Tudo do plano Essencial','Até 25 páginas','Portefólio de projetos e clientes','Versão preparada para impressão','Ronda extra de revisão']),
            ('Premium','Para concursos e mercados internacionais.',None,['Tudo do plano Profissional','Versão em inglês','Apresentação institucional a condizer','Versão digital interativa'])]),
   dict(slug='propostas-e-concursos',nome='Propostas Comerciais e de Concursos',longo='Desenvolvimento de Propostas Comerciais e de Concursos',inclui='Checklist de desenvolvimento, proposta técnica e checklist de submissão',preco='18.500 MT',unid='',
    resumo='Propostas construídas a partir dos critérios de avaliação, para concorrer com argumento e entregar sem falhas.',
    planos=[('Essencial','Para uma proposta bem montada e entregue a tempo.','18.500 MT',['Checklist de desenvolvimento','Proposta técnica','Checklist de submissão','Revisão final antes da entrega']),
            ('Profissional','Para concursos com muitos critérios.',None,['Tudo do plano Essencial','Análise do caderno de encargos e dos critérios','Estrutura da proposta financeira','Paginação com a identidade da marca']),
            ('Premium','Para quem concorre com frequência.',None,['Tudo do plano Profissional','Acompanhamento até à submissão','Pedidos de esclarecimento à entidade','Modelos para as próximas propostas'])]),
  ]),
 dict(slug='marketing-e-vendas',nome='Marketing & Vendas',andar=3,rot='Andar 3',pilar='a-marketing',ico='i-funil',sub='Um motor comercial',
  tese='Um motor comercial que trabalha todos os meses.',
  texto='Estruturamos o posicionamento, os canais e o processo de vendas para que a sua empresa gere oportunidades de forma previsível e converta mais do que gera.',
  servicos=[
   dict(slug='expert-led-growth',nome='Expert Led Growth',longo='Expert Led Growth',inclui='Marca pessoal, posicionamento e monetização · 3 meses',preco='65.200 MT',unid='',
    resumo='Para especialistas e líderes que querem transformar o que sabem em marca, autoridade e receita.',
    planos=[('Essencial','Para definir a marca e o caminho.','65.200 MT',['Programa de 3 meses','Diagnóstico da marca pessoal','Posicionamento e mensagem','Estratégia de conteúdo','Plano de monetização']),
            ('Profissional','Para ganhar presença todos os meses.',None,['Tudo do plano Essencial','Produção de conteúdo mensal','Gestão de LinkedIn e Instagram','Sessões quinzenais de acompanhamento']),
            ('Premium','Para lançar uma oferta própria.',None,['Tudo do plano Profissional','Criação da oferta: curso, mentoria ou consultoria','Lançamento da oferta','Sessão fotográfica e vídeo de apresentação'])]),
   dict(slug='brand-121',nome='Brand 121',longo='Brand 121',inclui='Estratégia de marca · 4 meses de execução',preco='135.000 MT',unid='',
    resumo='A estratégia de marca da sua empresa, desenhada e posta em prática connosco durante 4 meses.',
    planos=[('Essencial','Para dar à marca uma direção clara.','135.000 MT',['Diagnóstico da marca e do mercado','Posicionamento, proposta de valor e mensagem','Plano de marketing','4 meses de execução acompanhada','Relatório mensal de resultados']),
            ('Profissional','Para marcas que vão a campanha.',None,['Tudo do plano Essencial','Revisão da identidade visual','Campanhas digitais geridas','Reuniões semanais com a equipa']),
            ('Premium','Para ligar a marca às vendas.',None,['Tudo do plano Profissional','Processo e funil de vendas','Treinamento da equipa comercial','Painel de indicadores comerciais'])]),
   dict(slug='mediatrack',nome='MediaTrack',longo='MediaTrack',inclui='Produção de conteúdo e gestão de redes sociais · contrato mínimo de 3 meses',preco='15.000 MT',unid='',faixa='15.000 – 35.000 MT',
    resumo='Conteúdo regular e redes sociais geridas, para a sua empresa estar presente onde os clientes estão.',
    planos=[('Essencial','Para manter as redes ativas.','15.000 MT',['Gestão de 2 redes sociais','Calendário editorial mensal','12 publicações por mês','Relatório mensal','Contrato mínimo de 3 meses, pago no início de cada mês']),
            ('Profissional','Para crescer com vídeo.',None,['Gestão de 3 redes sociais','20 publicações por mês','Vídeos curtos (reels)','Resposta a comentários e mensagens','Relatório mensal']),
            ('Premium','Para uma presença completa.','35.000 MT',['Gestão de 4 redes sociais','30 publicações por mês','Produção de vídeo e fotografia','Campanhas pagas geridas','Reunião mensal de resultados'])]),
  ]),
 dict(slug='desenvolvimento-tecnologico',nome='Desenvolvimento Tecnológico',andar=4,rot='Andar 4',pilar='a-tecnologia',ico='i-codigo',sub='Sistemas e automação',
  tese='Tecnologia ao serviço da operação.',
  texto='Desenvolvemos sites, sistemas e automações que tiram trabalho manual da sua equipa e põem a informação certa nas mãos de quem decide.',
  provisorios=[('Sites e landing pages','Rápidos e feitos para converter. Manutenção mensal desde 1.500 MT.','15.000 MT'),('Sistemas à medida','Para a forma como a sua empresa trabalha. Manutenção mensal desde 5.000 MT.','95.000 MT'),('Automação de processos','Pedidos, aprovações e relatórios sozinhos')]),
 dict(slug='assessoria-corporativa',nome='Assessoria Corporativa',andar=5,rot='Andar 5',pilar='a-treinamento',ico='i-capelo',sub='Equipas preparadas',
  tese='Equipas preparadas para vender e gerir.',
  texto='Treinamos as suas equipas de vendas e atendimento e formamos quem as gere, para que o resultado fique na empresa.',
  servicos=[
   dict(slug='treinamento-de-vendas',nome='Treinamento de Vendas',longo='Treinamento de Vendas',inclui='3 dias de formação · cada pessoa a mais: 3.500 MT',preco='26.500 MT',unid='até 10 pessoas',
    resumo='Para equipas de vendas e de atendimento que querem abordar, argumentar e fechar com método.',
    planos=[('Essencial','O método, em sala.','26.500 MT',['Até 10 pessoas, 3 dias de formação','Abordagem e argumentação','Atendimento e tratamento de objeções','Material de apoio','Certificado de participação']),
            ('Profissional','O método aplicado à sua empresa.',None,['Tudo do plano Essencial','Diagnóstico prévio da equipa','Exercícios com casos reais da empresa','Guiões de venda personalizados']),
            ('Premium','O método no terreno.',None,['Tudo do plano Profissional','Acompanhamento no terreno','Sessão de reforço após 30 dias','Relatório de evolução da equipa'])]),
   dict(slug='gestao-comercial-e-marketing',nome='Formação em Gestão Comercial e Marketing',longo='Formação em Gestão Comercial e Marketing',inclui='Para gestores comerciais e de marketing',preco='45.000 MT',unid='',
    resumo='Para gestores comerciais e de marketing que lideram equipas, metas e orçamentos.',
    planos=[('Essencial','Os fundamentos da gestão comercial.','45.000 MT',['Planeamento comercial e metas','Gestão e motivação de equipas','Marketing e posicionamento','Indicadores e relatórios','Certificado de participação']),
            ('Profissional','A formação aplicada ao seu plano.',None,['Tudo do plano Essencial','Plano comercial da empresa construído na formação','Sessões individuais de mentoria','Modelos e ferramentas de gestão']),
            ('Premium','Da formação aos resultados.',None,['Tudo do plano Profissional','Acompanhamento durante 3 meses','Revisão de resultados com a direção'])]),
  ]),
]
